UNIT
ITMO-NSS-team/GEFEST pull request #14
Opened 2022-01-14 13:10 UTC by DenisSidoren

unit test for 1st func of Geometry2D

2022-01-19 13:01 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    def resize_poly_test():
убрал вложенную функцию, по поводу общих переменных будет дальше ясно как их лучше использовать с другими функциями

2022-01-19 13:02 UTC, DenisSidoren commented on test/test_geometry2D.py
> +        poly = domain.bound_poly()
добавил координаты квадрата в Domain() через allowed_area, надеюсь это так делается

2022-01-19 13:03 UTC, DenisSidoren commented on test/test_geometry2D.py
> +        assert square_difference != 0
вручную посчитал площадь при масштабировании стороны квадрата и в assert сравниваю эти величины

2022-01-19 13:07 UTC, nicl-nno commented on test/test_geometry2D.py
> +def test_Geometry2d():
Вроде ничего не изменилось.

2022-01-19 13:13 UTC, pep8speaks commented
Hello @DenisSidoren! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/test_geometry2D.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py):

> [Line 9:1](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L9): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 13:33](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L13): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 13:35](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L13): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 18:51](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L18): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 19:43](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L19): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 19:51](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L19): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 20:80](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 23:50](https://github.com/ITMO-NSS-team/GEFEST/blob/e1e66df117ab25db3faca23ff2f2819455488b2d/test/test_geometry2D.py#L23): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-01-19 13:35 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/150141055-f790a144-ecbd-4c92-8e17-0f40faad6c27.png)

Обрати внимание ещё на авто-замечания по code style.

2022-01-19 17:24 UTC, nicl-nno requested changes

2022-01-19 17:24 UTC, nicl-nno commented on test/test_geometry2D.py
> +    square_hands_calc = ((a*x_scale) * (b*y_scale)) - a*b
Хорошо бы переменные назвать в более "тестовой" логике, в стиле observed_difference / expected_difference. Тогда проверка будет понятнее.

2022-01-19 17:24 UTC, nicl-nno commented on test/test_geometry2D.py
> +    new_poly = geometry.resize_poly(poly, x_scale= x_scale, y_scale= y_scale)
Чтобы была понятнее логика теста, лучше называть в стиле original_poly / resized_poly.

Пробелы после = выглядят лишними (да и не только здесь). В pycharm это можно править через ctrl+alt+l

2022-01-19 17:24 UTC, nicl-nno commented on test/test_geometry2D.py
> +    a = b = 10
Лучше иметь разные стороны, чтобы проверямый случай был более сложен.

2022-01-21 10:41 UTC, nicl-nno commented on test/test_geometry2D.py
> +    assert np.isclose(observed_difference, expected_difference) == True
== True тут излишне.

2022-01-21 10:42 UTC, nicl-nno commented on test/test_geometry2D.py
> +    new_poly = geometry.resize_poly(poly, x_scale= x_scale, y_scale= y_scale)
>пробелы подогнал под PEP8, они все-таки нужны, вот пруфы: https://www.python.org/dev/peps/pep-0008/#other-recommendations

Я про вот эту ситуацию:

![image](https://user-images.githubusercontent.com/5711814/150513410-42dfd90b-62fb-4602-a92b-98bbfc474cd0.png)

PEP8bot выше дает ссылки на конкретные ошибки.

2022-01-21 10:46 UTC, nicl-nno commented on test/test_geometry2D.py
> +    y_scale = np.random.uniform(0,10)
Такое задание сторон может породить стохастичное поведение теста, что всегда плохо. Если хочешь реализовать несколько варианто входных данных - это можно делать [так](https://stackoverflow.com/questions/66867647/pytest-run-same-tests-for-different-sets-of-input-data).

2022-01-27 09:56 UTC, DenisSidoren reviewed
в том примере предлагается, на сколько я понимаю, один и тот же тест запускать с разными наборами данных.. я хотел вместо 10-20-30 поставить рандомные характеристики прямоугольника. Если вопрос конкретно в uniform, нормально ли будет использовать randint?

2022-01-27 09:56 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    y_scale = np.random.uniform(0,10)
в том примере предлагается, на сколько я понимаю, один и тот же тест запускать с разными наборами данных.. я хотел вместо 10-20-30 поставить рандомные характеристики прямоугольника. Если вопрос конкретно в uniform, нормально ли будет использовать randint?

2022-01-27 09:59 UTC, nicl-nno commented on test/test_geometry2D.py
> +    y_scale = np.random.uniform(0,10)
>один и тот же тест запускать с разными наборами данных

Одно дело - запускать с разными, другое дело - со случайными. Если есть какой-то один вариант входных данных, на который тест падает - то ты не сможешь это стабильно воспроизвести, если данные генерируются случайно и каждый раз по новому.

2022-01-27 10:06 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    y_scale = np.random.uniform(0,10)
ок, понял, пока верну числа на место, потом видно будет

2022-01-27 15:48 UTC, DenisSidoren reviewed
у меня (скорее всего у меня) проблема - тесты не проходят проверку

 test_resize_poly: площадь масштабированного полигона равна площади ориджин

test_rotate_poly: полигоны не равны при повороте на 90 градусов. Я рассчитал координаты, которые должны получиться при повороте "из центра".
Сначала сделал поворот на 180 и такой тест завершается успешно, но это примитивно

2022-01-27 18:45 UTC, nicl-nno commented on test/test_geometry2D.py
> +    expected_poly = expected_domain.bound_poly
Опять же, зачем опираться на bound_poly для domain? Поворачивай конкретный полигон по аналогии с предыдущим тестом.

2022-01-27 18:46 UTC, nicl-nno commented on test/test_geometry2D.py
> +    assert expected_poly == rotate_poly
Это точно проверяет равеноство полигонов в геометрическом смысле, а не ссылки не объекты?

2022-01-27 20:04 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    expected_poly = expected_domain.bound_poly
Так а как еще создать полигон, если не через bound_poly? я понимаю, что можно через импорт Polygon, но это ведь одно и то же. 

Я использую тот же полигон, что и в первом тесте как ориджинал

2022-01-27 20:06 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    assert expected_poly == rotate_poly
В этом тесте происходит поворот фигуры. Исхожу из логики, что при повороте нам важно, чтобы координаты фигуры оказались на своем месте, поэтому вручную рассчитал новые координаты полигона, который получится при повороте ориджинал на 90 градусов..

2022-01-27 20:07 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    assert expected_poly == rotate_poly
Если ориджинал повернуть на 180 градусов и в тесте прописать равенство ориджинал и rotated полигона, то тест проходит успешно

2022-01-27 20:38 UTC, nicl-nno commented on test/test_geometry2D.py
> +import pytest
Импорт лишний

![image](https://user-images.githubusercontent.com/5711814/151439798-8257a576-8ef5-4faa-abce-729e1f4af15e.png)

2022-01-27 20:40 UTC, nicl-nno commented on test/test_geometry2D.py
> +    expected_poly = expected_domain.bound_poly
>это ведь одно и то же.

Разница в семантике. Domain - это класс для всей области оптимизации. Есть возможность извлечь окружающий её полигон, но нет необходимости вовлекать в unit-тест лишнюю сущность.

2022-01-27 20:45 UTC, nicl-nno commented on test/test_geometry2D.py
> +    assert expected_poly == rotate_poly
Тем не менее, судя по отладчику - здесь сравниваются именно ссылки на объекты Polygon, а не их значения (координаты точек).

По поводу проверки координат - обрати внимании, что они везде округляются до целых (т.к.  при задании сетки предполагается, что изменения меньше 1 незначимы).

2022-01-27 20:49 UTC, nicl-nno commented
>test_resize_poly: площадь масштабированного полигона равна площади ориджин

Обрати внимание, что методы Geometry2D меняют полигон in-place. Поэтому и площади одинаковы.

В целом, это не совсем ожидаемое поведение, поэтому можешь переработать методы, чтобы они создавали возвращаемый Polygon с нуля.

2022-01-28 13:36 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    new_poly = geometry.resize_poly(poly, x_scale= x_scale, y_scale= y_scale)
исправлено

2022-01-28 13:37 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    expected_poly = expected_domain.bound_poly
понял

2022-01-28 15:50 UTC, DenisSidoren commented on test/test_geometry2D.py
> +import pytest
убрал

2022-01-28 15:52 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    assert expected_poly == rotate_poly
Действительно, сравнивались Point как классы, пофиксил, сравниваются сами точки теперь.

За координаты прямоугольника взял целые числа

2022-01-28 16:10 UTC, nicl-nno requested changes

2022-01-28 16:10 UTC, nicl-nno commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
Вроде можно упросить как all([rotated_first == coord_second for x,y in zip(rotated_coords, expected_coords)])

2022-01-28 16:10 UTC, nicl-nno commented on test/test_geometry2D.py
> +b = 20
Для понятности назови их poly_width/poly_height, если речь именно о них.

2022-01-28 16:10 UTC, nicl-nno commented on test/test_geometry2D.py
> +rectange_poly = Polygon('rectangle', points=[Point(*coords) for coords in rectangle_points])
лучше назвать initial_poly или как-то так.

2022-01-28 16:10 UTC, nicl-nno commented on test/test_geometry2D.py
> +
![image](https://user-images.githubusercontent.com/5711814/151580994-a83c39a9-0a66-4272-902f-6f51c934b601.png)

Ну и оформление-то победи.

2022-01-28 16:10 UTC, nicl-nno commented on test/test_geometry2D.py
> +    def getting_coords(points):
Тогда уж exctract_coords или как-то так. 
Но кажется это вообще не особо нужно - можно сравнивать и без преобразования.

2022-01-28 20:08 UTC, DenisSidoren commented on test/test_geometry2D.py
> +
done))

2022-01-28 20:12 UTC, DenisSidoren commented on test/test_geometry2D.py
> +rectange_poly = Polygon('rectangle', points=[Point(*coords) for coords in rectangle_points])
назвал так исходя из мысли, что для дальнейших тестов могут потребоваться другие фигуры, предлагаю пока оставить этот вопрос открытым

2022-02-03 11:54 UTC, DenisSidoren commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
сделал

2022-02-03 12:06 UTC, DenisSidoren commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
да, но в таком случае важен порядок координат, а он в rotated и expected иногда не совпадает

2022-02-03 12:10 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    def getting_coords(points):
мы говорили, что Points сравниваются по классу, этой функцией я вытаскиваю значения координат и делаю объекты итерируемыми, чтобы потом assert мог это кушать (опять же, вне зависимости от порядка расстановки внутри списка)

2022-02-03 14:06 UTC, nicl-nno commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
Вроде логика проверок одинакова. Все равно же для корректного assert-а нужно чтобы все элементы списка были True.

2022-02-03 14:06 UTC, nicl-nno commented on test/test_geometry2D.py
> +    def getting_coords(points):
Ты можешь в ходе итерации сравнивать поля x и y и для экзампляров Point.

2022-02-03 14:07 UTC, nicl-nno commented on test/test_geometry2D.py
> +
![image](https://user-images.githubusercontent.com/5711814/152358343-86e04675-2ad0-4555-824d-bf808d382b7b.png)

Ну вот по прежнему не done.

2022-02-03 14:35 UTC, DenisSidoren commented on test/test_geometry2D.py
> +b = 20
сделано

2022-02-03 15:21 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    def getting_coords(points):
отдельно x, отдельно y имеется ввиду?

2022-02-03 15:24 UTC, nicl-nno commented on test/test_geometry2D.py
> +    def getting_coords(points):
Имеется в виду что-то вроде pt1.x == pt2.x and pt1.y == pt2.y

2022-02-03 15:25 UTC, DenisSidoren commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
да, только сравнение пар x,y идет перебором а значит [(0,0), (10,10), (0,10)] при сравнении с [(0,10),(0,0), (10,10)]  даст False трижды

2022-02-03 15:25 UTC, DenisSidoren commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
хотя по факту нет никакой разницы в фигурах с этими координатами

2022-02-03 15:27 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    def getting_coords(points):
это к вопросу о порядке записи координат, что мы обсуждаем выше

2022-02-03 15:50 UTC, nicl-nno commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
Если ты хочешь проверить, что все элементы одного списка сходят в другой - то можно просто set(rotated_coords).issubset(expected_coords) and len(rotated_coords) == len(expected_coords)

2022-02-03 15:51 UTC, nicl-nno commented on test/test_geometry2D.py
> +    assert geometry.is_contain_point(figure, expected_point)
Тут бы хорошо проверять ещё и альтернативный вариант случай - точку, не входящую в полигон.

2022-02-03 20:14 UTC, DenisSidoren commented on test/test_geometry2D.py
> +                expected_coords != rotated_coords]
исправил

2022-02-03 20:15 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    def getting_coords(points):
функцию убрал

2022-02-03 20:41 UTC, DenisSidoren commented on test/test_geometry2D.py
> +
победил?!

2022-02-03 20:42 UTC, DenisSidoren commented on test/test_geometry2D.py
> +    assert geometry.is_contain_point(figure, expected_point)
сделал такую проверку

2022-02-03 20:58 UTC, nicl-nno commented on test/test_geometry2D.py
> +
Ага

2022-02-03 20:59 UTC, nicl-nno commented on test/test_geometry2D.py
> +    assert geometry.is_contain_point(figure, expected_point) is False
Можно просто assert not ...

2022-02-03 21:00 UTC, nicl-nno approved these changes
Можно мержить. Не забудь при объединении коммитов убрать лишние фрагменты описания.

2022-02-04 10:56 UTC, merged