Unit
ITMO-NSS-team/GEFEST pull request #20
Opened 2022-02-09 07:45 UTC by DenisSidoren

предлагаю свой вариант функции nearest_point вместо имеющихся двух

2022-02-09 07:45 UTC, pep8speaks commented
Hello @DenisSidoren! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/test_geometry2D.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/bb2df05affddb287aa7d0329819e44edb80e68e7/test/test_geometry2D.py):

> [Line 81:66](https://github.com/ITMO-NSS-team/GEFEST/blob/bb2df05affddb287aa7d0329819e44edb80e68e7/test/test_geometry2D.py#L81): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 86:62](https://github.com/ITMO-NSS-team/GEFEST/blob/bb2df05affddb287aa7d0329819e44edb80e68e7/test/test_geometry2D.py#L86): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-02-09 08:43 UTC, nicl-nno commented
Пока общие комментарии:

1) опять лишний коммит есть
2) называй PR-ы и ветки более конкретно, чем просто Unit

2022-02-09 09:25 UTC, DenisSidoren commented
название поменял, за лишний коммит сорян, я пытаюсь укротить гитхаб, надеюсь всё получится)

2022-02-09 10:07 UTC, nicl-nno requested changes

2022-02-09 10:07 UTC, nicl-nno commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Это не нужно коммитить.

2022-02-22 13:04 UTC, nicl-nno commented on gefest/core/geometry/geometry_2d.py
> +        if type(nearest_obj) == Point:
Лучше отписывайте о исправлениях когда уже отправлен соответствующий коммит - а то возникает путаница.

2022-02-22 17:50 UTC, DenisSidoren commented on test/test_geometry2D.py
> +@pytest.mark.parametrize("figure_1, figure_2, expected_point",
в фикстурах одинаковые вроде везде, или речь вообще про все кавычки в мире?

2022-02-22 17:54 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
>          return Point(nearest_correct_position.x, nearest_correct_position.y)
старая версия не могла работать. метод shapely возвращает пару точек по одной для каждого объекта

<img width="839" alt="Снимок экрана 2022-02-22 в 20 53 25" src="https://user-images.githubusercontent.com/70846761/155190681-02930640-50ce-4732-971a-2f13713aa072.png">

2022-02-22 17:56 UTC, DenisSidoren commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
это ошибка, случайно залетел

2022-02-22 17:57 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
> +    def nearest_point(self, nearest_obj: Point or Polygon, poly: Polygon) -> Point:
да, исправил

2022-02-22 18:08 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
> -    def nearest_points(self, poly_1: Polygon, poly_2: Polygon) -> List[Point]:
у меня почему-то не работает поиск по проекту в pycharm, попробую пофиксить, в Geometry добавил

2022-02-25 08:59 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
> -    def nearest_points(self, poly_1: Polygon, poly_2: Polygon) -> List[Point]:
по проекту посмотрел, исправил там, где подразумевалось использование этой функции

2022-02-25 10:04 UTC, nicl-nno commented on gefest/core/geometry/geometry_2d.py
> +        if method is None:
А почему просто не задать это как значение по умолчанию?

2022-02-25 10:04 UTC, nicl-nno commented on gefest/core/geometry/geometry_2d.py
> +        geom_convex = method_variants[method]
Нужно обработать вариант, когда метод задан неправильно (NonImplementedException, например)

2022-02-25 10:05 UTC, nicl-nno commented on test/test_geometry2D.py
> +@pytest.mark.parametrize("figure_1, figure_2, expected_point",
Про все в мире, если нет явной потребности в разных.

2022-02-25 12:37 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
> +        if type(nearest_obj) == Point:
исправлено

2022-02-25 12:37 UTC, DenisSidoren commented on test/test_geometry2D.py
> +@pytest.mark.parametrize("figure_1, figure_2, expected_point",
исправлено

2022-02-25 12:37 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
> +        if method is None:
исправлено

2022-02-25 12:38 UTC, DenisSidoren commented on gefest/core/geometry/geometry_2d.py
> +        geom_convex = method_variants[method]
сделано

2022-02-25 12:44 UTC, nicl-nno commented on gefest/core/geometry/geometry_2d.py
> +        if method in list(method_variants.keys()):
Кажется можно просто method in method_variants

2022-02-25 12:45 UTC, nicl-nno commented on gefest/core/geometry/geometry_2d.py
> +            raise KeyError(f'Unknown method, use one of followed: {list(method_variants.keys())}')
Можно ещё указать название unknown method-а для простоты отладки

2022-02-25 12:46 UTC, nicl-nno approved these changes

2022-02-25 14:52 UTC, merged