Unit tests for crossover, mutation
ITMO-NSS-team/GEFEST pull request #25
Opened 2022-04-25 10:53 UTC by DenisSidoren

2022-04-25 10:53 UTC, pep8speaks commented
Hello @DenisSidoren! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`gefest/core/opt/operators/crossover.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/db5376707f150372a9bc30c7092724ccfae5cad7/gefest/core/opt/operators/crossover.py):

> [Line 57:7](https://github.com/ITMO-NSS-team/GEFEST/blob/db5376707f150372a9bc30c7092724ccfae5cad7/gefest/core/opt/operators/crossover.py#L57): [E271](https://duckduckgo.com/?q=pep8%20E271) multiple spaces after keyword

2022-04-26 11:47 UTC, nicl-nno requested changes

2022-04-26 11:47 UTC, nicl-nno commented on test/test_crossover.py
> +def test_crossover_true():
Вместо true/false лучше как-то иначе незвать, чтобы было понятней.

2022-04-26 11:47 UTC, nicl-nno commented on test/test_crossover.py
> +    expected_structure = [structure_1.polygons[0].points, structure_2.polygons[1].points]
Но это вроде не structure, а список наборов точек. Тоже видимо как-то иначе нужно назвать.

2022-04-26 11:47 UTC, nicl-nno commented on test/test_crossover.py
> +            assert True
Кажется, такой тест никогда не упадет. Нужно проверять, был ли успешный кроссовер хоть и на результат проверки делать assert после цикла.

2022-04-26 11:47 UTC, nicl-nno commented on test/test_mutation.py
> +            assert True
Аналогично про проверку. В идеале бы ещё протестировать каждый вид мутации отдельно (например, можно проверять что мутация на поворот не меняет число точек и площадь.)

2022-04-26 11:47 UTC, nicl-nno commented on gefest/core/opt/operators/crossover.py
> +        # In the case when any structures consist of only one polygon,
Тут кажется правильное будет "any of structures consists"

2022-04-26 11:47 UTC, nicl-nno commented on test/test_crossover.py
> +    rectangle_poly = Polygon(f'rectangle from {x,y}', points=[Point(*coords) for coords in rectangle_points])
Кмк лучше id делать без пробелов.

2022-04-26 11:47 UTC, nicl-nno commented on test/test_crossover.py
> +structure_2 = Structure([create_rectangle(15, 5), create_rectangle(15, 15)])
Может их назвать structure_large и structure_small? Можно ради этого даже размнеры немного поменять. И тогда можно будет проверить, что после кроссовера площадь меньше large и больше small.

2022-04-26 12:20 UTC, DenisSidoren commented on test/test_crossover.py
> +    rectangle_poly = Polygon(f'rectangle from {x,y}', points=[Point(*coords) for coords in rectangle_points])
ок

2022-04-26 12:21 UTC, DenisSidoren commented on gefest/core/opt/operators/crossover.py
> +        # In the case when any structures consist of only one polygon,
ок

2022-04-26 12:21 UTC, DenisSidoren commented on test/test_crossover.py
> +def test_crossover_true():
ок

2022-04-26 14:19 UTC, DenisSidoren commented on test/test_mutation.py
> +            assert True
вроде сделал

2022-04-26 14:53 UTC, nicl-nno commented on test/test_mutation.py
> +        elif any(compared_points) and not any(compared_square):
А почему при resize вершины совпадают? Я думал масштабирование идет относительно центра фигуры и вершины тоже смещаются. Или нет?

2022-04-26 14:54 UTC, DenisSidoren commented on test/test_mutation.py
> +        elif any(compared_points) and not any(compared_square):
не должны совпадать, опечатался

2022-04-26 15:02 UTC, nicl-nno commented on test/test_crossover.py
> +    assert crossover_counts > 0
Аналогично - можно цикл останавливать сразу как произошел хоть один успешный.

2022-04-26 15:05 UTC, DenisSidoren commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
хороша шутка)) у structure есть size, которое дает сумму точек всех полигонов

2022-04-26 15:05 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +    def _add_poly():
Лучше вынести таких методы наружу в сам скрипт, а не делать вложенными.

2022-04-26 15:07 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +        if random.random() < polygon_add_mutation_prob and \
Раз уж эта часть модифицируется - хорошо бы с самого начала выбирать, какая именно мутация будет применена. Иначе вероятности, проверяемые по порядку, учитываются довольно неочевидно.

2022-04-26 15:11 UTC, nicl-nno commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
Можно поименовать поля как num_points и num_poly, чтобы было очевидней.

2022-04-26 15:16 UTC, DenisSidoren commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
@property
    def size(self):
        return sum([len(p.points) for p in self.polygons])

в structure есть такая штука, но кажется будет полезнее не суммировать, а оставить список точек по каждому полигону и назвать например poly_points

2022-04-26 18:12 UTC, nicl-nno commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
>оставить список точек по каждому полигону и назвать например poly_points
Ну это какой-то очень специфический случай - такой список и так в каждом полигоне хранится.

А size я и предлагаю переименовать, чтобы было понятнее, что в нем считается.

2022-04-27 07:57 UTC, DenisSidoren commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
сделал

2022-04-27 07:58 UTC, DenisSidoren commented on test/test_mutation.py
> +                count_rotated_poly > 0, count_resize_poly > 0])
сделал

2022-04-27 09:33 UTC, nicl-nno commented on gefest/core/structure/structure.py
> +        return sum([len(p.points) for p in self.polygons])
Тут кажется дублирование.

2022-04-27 09:36 UTC, nicl-nno commented on test/test_mutation.py
> +                break
Вернулись к предыдущей ситуации - такой тест никогда не упадет, даже если ни одной мутации не случится

2022-04-27 09:37 UTC, nicl-nno commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
Вроде ничего не поменялось.

2022-05-06 13:22 UTC, DenisSidoren commented on test/test_mutation.py
> +                break
не понимаю, почему? assert True происходит сразу после того, как каждой мутации случилось хотя бы по разу

2022-05-06 13:22 UTC, DenisSidoren commented on test/test_mutation.py
> +        count_initial_points = [len(p.points) for p in structure.polygons]
исправлено

2022-05-06 13:23 UTC, DenisSidoren commented on test/test_crossover.py
> +    assert crossover_counts > 0
исправил

2022-05-06 13:24 UTC, DenisSidoren commented on gefest/core/opt/operators/mutation.py
> +    def _add_poly():
вынес

2022-05-06 13:24 UTC, nicl-nno commented on test/test_mutation.py
> +                break
Если это условие ни разу не выполнится - то тест все равно успешно завершиться, т.к нет неудачных ассертов.

2022-05-06 13:24 UTC, DenisSidoren commented on gefest/core/opt/operators/mutation.py
> +    mutation_func()
исправил

2022-05-06 13:26 UTC, DenisSidoren commented on gefest/core/opt/operators/mutation.py
> +        if random.random() < polygon_add_mutation_prob and \
переделал структуру файла, почему-то не проходит test_circle, скорее всего не может найти решение после моих модификаций mutation.py, по этому вопросу мне нужна помощь..

2022-05-06 13:26 UTC, DenisSidoren commented on gefest/core/structure/structure.py
> +        return sum([len(p.points) for p in self.polygons])
да, случайно залетел

2022-05-06 15:48 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +        if random.random() < polygon_add_mutation_prob and \
Но в test_circle качество решения никак не проверяется. Судя по всему, там просто что-то зацикливается в get_pop_worker - попробуй отладчиком поймать.

2022-05-06 16:00 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +        if random.random() < polygon_add_mutation_prob and \
Сходу get_random_poly всегда выдает None, может в нем дело.

2022-05-12 14:18 UTC, DenisSidoren commented on gefest/core/opt/operators/mutation.py
> +        if random.random() < polygon_add_mutation_prob and \
нашел)

2022-05-13 13:30 UTC, DenisSidoren commented on test/test_mutation.py
> +                break
исправил

2022-05-13 13:45 UTC, nicl-nno commented on test/test_mutation.py
> +            assert True
![image](https://user-images.githubusercontent.com/5711814/168297029-45db0020-51af-421d-93bf-9e64d07198a0.png)

Кажется тут можно избежать дублирования, заменив первый assert на break

2022-05-16 08:14 UTC, DenisSidoren commented on test/test_mutation.py
> +            assert True
исправил

2022-05-17 12:33 UTC, nicl-nno approved these changes

2022-05-17 12:57 UTC, merged