Preserving of optimisation results implemented
ITMO-NSS-team/GEFEST pull request #37
Opened 2022-07-25 16:22 UTC by nicl-nno

Results of gen. dis. can be saved in JSON using Result class.

2022-07-25 16:22 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gefest/core/opt/operators/crossover.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/d2f6585fd006b358833b05090439ac114896094e/gefest/core/opt/operators/crossover.py):

> [Line 32:121](https://github.com/ITMO-NSS-team/GEFEST/blob/d2f6585fd006b358833b05090439ac114896094e/gefest/core/opt/operators/crossover.py#L32): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)







* In the file [`gefest/core/serialization/serializer.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/d2f6585fd006b358833b05090439ac114896094e/gefest/core/serialization/serializer.py):

> [Line 47:5](https://github.com/ITMO-NSS-team/GEFEST/blob/d2f6585fd006b358833b05090439ac114896094e/gefest/core/serialization/serializer.py#L47): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2022-07-27 12:10 UTC, DenisSidoren requested changes

2022-07-27 12:10 UTC, DenisSidoren commented on gefest/core/structure/polygon.py
> +            points = []
а какая цель создания полигона без точек?

2022-07-27 12:10 UTC, DenisSidoren commented on gefest/core/viz/struct_vizualizer.py
> -        plt.legend()
я этот модуль переделал и упростил уже

посмотри плиз  в моем  PR код, а выглядит результат работы этого модуля так:
https://gefest--35.org.readthedocs.build/en/35/components/visualization.html

2022-08-06 16:56 UTC, nicl-nno commented on gefest/core/viz/struct_vizualizer.py
> -        plt.legend()
Взял из твоего кода.

2022-08-06 16:56 UTC, nicl-nno commented on gefest/core/structure/polygon.py
> +            points = []
Чтобы потом уже в него эти точки добавлять. Не помню уже, где именно это было нужно - но пусть будет для удобства.

2022-08-06 16:56 UTC, nicl-nno commented on gefest/core/serialization/serializer.py
> +        :return: dict[str, str] with path to the object
Поменял

2022-08-11 18:27 UTC, DenisSidoren approved these changes

2022-08-11 18:27 UTC, DenisSidoren commented on gefest/core/serialization/serializer.py
> +        """Gets the object type from the class_path
этот метод скрытый, зачем его документировать докстрингами?

если им можно пользоваться, то почему он не может быть обычным?

2022-08-11 18:27 UTC, DenisSidoren commented on gefest/core/serialization/serializer.py
> +            json_obj: dict[str, Any] to be decoded into Python class, function or
типы объектов принималось обозначать через ``type``, то есть ``dict[str, Any]``
в таком случае этот объект будет в симпатишном квадратике

2022-08-11 18:27 UTC, DenisSidoren commented on gefest/core/serialization/serializer.py
> +            json_obj: dict[str, Any] to be decoded into Python class, function or
при этом сами объекты, например Point, Domain и прочее, вот так ->       :obj:`Domain`

2022-08-18 16:00 UTC, nicl-nno commented on gefest/core/serialization/serializer.py
> +        """Gets the object type from the class_path
Документировать не обязательно, но лишним не будет. В таком виде взял из FEDOT-а.

2022-08-18 16:05 UTC, nicl-nno commented on gefest/core/serialization/serializer.py
> +            json_obj: dict[str, Any] to be decoded into Python class, function or
Пока просто убрал дублирующую type hint-ы типизацию.

2022-08-18 16:10 UTC, merged