paper updates
ITMO-NSS-team/GEFEST pull request #42
Opened 2022-09-04 22:25 UTC by quickjkee

2022-09-04 22:25 UTC, pep8speaks commented
Hello @quickjkee! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:























































* In the file [`cases/synthetic/circle/configuration/circle_optimizer.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/circle/configuration/circle_optimizer.py):

> [Line 28:21](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/circle/configuration/circle_optimizer.py#L28): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`cases/synthetic/circle/configuration/circle_sampler.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/circle/configuration/circle_sampler.py):

> [Line 19:19](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/circle/configuration/circle_sampler.py#L19): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file







* In the file [`cases/synthetic/line/configuration/line_optimizer.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/line/configuration/line_optimizer.py):

> [Line 28:21](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/line/configuration/line_optimizer.py#L28): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`cases/synthetic/line/configuration/line_sampler.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/line/configuration/line_sampler.py):

> [Line 19:19](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/cases/synthetic/line/configuration/line_sampler.py#L19): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file













































* In the file [`gefest/tools/optimizers/optimizer.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/optimizers/optimizer.py):

> [Line 24:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/optimizers/optimizer.py#L24): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`gefest/tools/samplers/DL/heat/heat_sampler.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/heat/heat_sampler.py):

> [Line 8:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/heat/heat_sampler.py#L8): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 9:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/heat/heat_sampler.py#L9): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 10:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/heat/heat_sampler.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

* In the file [`gefest/tools/samplers/DL/microfluid/aae.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/aae.py):

> [Line 147:68](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/aae.py#L147): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 161:13](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/aae.py#L161): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 213:48](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/aae.py#L213): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 218:13](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/aae.py#L218): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 239:88](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/aae.py#L239): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets

* In the file [`gefest/tools/samplers/DL/microfluid/backbones.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/backbones.py):

> [Line 197:20](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/backbones.py#L197): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`gefest/tools/samplers/DL/microfluid/microfluid_sampler.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/microfluid_sampler.py):

> [Line 8:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/microfluid_sampler.py#L8): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 9:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/microfluid_sampler.py#L9): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 10:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/microfluid_sampler.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/microfluid_sampler.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 12:1](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/gefest/tools/samplers/DL/microfluid/microfluid_sampler.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file





* In the file [`setup.py`](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/setup.py):

> [Line 53:2](https://github.com/ITMO-NSS-team/GEFEST/blob/2f34392b0e841d27bb45dfb6aa18bc8b6f7ec614/setup.py#L53): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-09-05 11:19 UTC, nicl-nno requested changes
Общие комментарии помимо тех что в коде:

1)В наборе коммитов всё ещё есть лишние (например, мои январские). Возможно часть лишних файлов - из-за них. Предлагаю для удобства схлопнуть все твои правки в 1 коммит. 
Алсо, у тебя есть права на этот репозиторий, т.ч. не обязательно из форка работать.

2) Всякие tmp_images - они нужны? Если они служат в качестве примеров - стоит это отразить в названии. Если не нужны - то удалить.

3) Там по мелочи есть предупрежддения по PEP8 - поправь плз.

4) Кое-где у функций и классов потерялись докстринги, type hint-ы и т.п. Если они актуальны - то перенеси их в свою ветку, если нет - то скорректируй или оставь TODO.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/core/algs/geom/validation.py
> -    """
Кое-где у функций и классов потерялись докстринги. Если они актуальны - то перенеси их к себе, если нет - то скорректируй или оставь TODO.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/core/algs/geom/validation.py
> +    if poly_1 is poly_2 or len(poly_1.points) == 0 or len(poly_2.points) == 0:
А если poly_1 is poly_2 - расстояние не должно быть 0?

2022-09-05 11:19 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +                             y_scale=np.random.uniform(0.25, 3, 1)[0])
Вариант с выделеннными функциями для отдельных видов мутации, который был до этого, читается и тестируется гораздо лучше. Если он функционально не противоречит твоему - можно использовать его, если противоречит - то лучше внести правки в него.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +    y_old = new_structure.polygons[polygon_to_mutate_idx].points[mutate_point_idx].y
А почему x_old, а не new?

2022-09-05 11:19 UTC, nicl-nno commented on gefest/core/structure/prohibited.py
> +        target_polygons = [list(Point(target).buffer(20).exterior.coords) for target in targets]
А тут точно не обойтись без шейплевской Point, используя только нашу? 
Конструкция с buffer(20) выглядит сложно понимаемой.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/core/viz/struct_vizualizer.py
> +        fitness = info['fitness']
На строку это заменяли чтобы можно было рисовать полигоны и не знаю для них фитнеса. Можно просто поддержать оба вариант, проверя тип?

2022-09-05 11:19 UTC, nicl-nno commented on gefest/tools/estimators/DL/bw_surrogate/bw_cnn.py
> +    Surrogate model for breakwaters task
А этот суррогат специфичен для BW task? Если нет - то лучше описать его более ещё. Если специфичен - то можно унаследовать BWSurrogate от общего CNNSurrogate и переместить его в cases?

Название в любом случе не очень удачное.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/tools/estimators/DL/heat/heat_cnn.py
> +class CNN:
Аналогично, я бы разделил общую реализацию и специфику heat.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/tools/estimators/estimator.py
> +    def __init__(self, estimator, loss: Optional[Callable] = None):
довольн странно что конструктор класса Estimator принимает на вход estimator с аналогичным интерфейсом. Возможно, тут лучше через наследование (или фабрику)?

2022-09-05 11:19 UTC, nicl-nno commented on gefest/tools/estimators/simulators/swan/swan_model/INPUT2
> +$***********MODEL INPUT*********************************
А оба конфига нужны? Я бы оставил один как пример.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/tools/estimators/simulators/swan/swan_model/PRINT
> +1
Это явно лишнее.

2022-09-05 11:19 UTC, nicl-nno commented on gefest/tools/samplers/sampler.py
> +        self.sampler = sampler
Наличие поля sampler  в sampler-е и дальшейшнее self.sampler.sample тоже смущает.

2022-09-05 12:46 UTC, nicl-nno commented on requirements.txt
> +bezier
Нужно ли убирать версию и нужен ли bezier вообще?

2022-09-16 15:56 UTC, quickjkee commented on README.md
> +<img src="./docs/img/gefest_logo.png" width="400"/>
удалил старый readme

2022-09-16 15:58 UTC, quickjkee commented on cases/breakwaters/configuration_de/bw_optimizer.py
> +def configurate_optimizer(pop_size: int,
ну да, они в большинстве своём специфичны. Но, думаю, что можно будет потом какую-нибудь хорошую обёртку сделать

2022-09-16 15:58 UTC, quickjkee commented on cases/breakwaters/main.py
> +opt = parser.parse_args()
Сделал общий конфиг для всех файлов

2022-09-16 15:59 UTC, quickjkee commented on gefest/core/algs/geom/validation.py
> -    """
Добавил докстринги, где потерялись

2022-09-16 16:00 UTC, quickjkee commented on gefest/core/opt/operators/mutation.py
> +                             y_scale=np.random.uniform(0.25, 3, 1)[0])
Почему-то при ребейзе откатило к старой мутации, сейчас вернул нормальную

2022-09-16 16:00 UTC, quickjkee commented on gefest/core/opt/operators/operators.py
> +    return EvoOperators(crossover=crossover, mutation=mutation)
ага

2022-09-16 16:01 UTC, quickjkee commented on gefest/tools/estimators/DL/bw_surrogate/bw_cnn.py
> +    Surrogate model for breakwaters task
Сделал немного специфичней

2022-09-16 16:02 UTC, quickjkee commented on gefest/tools/estimators/estimator.py
> +    def __init__(self, estimator, loss: Optional[Callable] = None):
да, не самая удачная обёртка. Позже сделаю более адекватным образом

2022-09-16 16:02 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_model/INPUT2
> +$***********MODEL INPUT*********************************
оставил один

2022-09-16 16:02 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_model/PRINT
> +1
убрал

2022-09-16 16:02 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_model/norm_end
> +  Normal end of run
убрал

2022-09-16 16:03 UTC, quickjkee commented on setup.py
> +URL = 'https://github.com/quickjkee/GEFEST'
отредактировал

2022-09-16 16:03 UTC, quickjkee commented on requirements.txt
> +bezier
исправил

2022-09-16 20:44 UTC, nicl-nno commented on gefest/core/opt/operators/mutation.py
> +                             y_scale=np.random.uniform(0.25, 3, 1)[0])
Но сейчас у тебя все равно add и remove склеены в одну. Может лучше таки оставить разделенные, как в master-е?

2022-09-16 20:54 UTC, nicl-nno commented on gefest/tools/estimators/simulators/swan/swan_model/PRINT
> +1
вроде нет?

2022-09-16 20:54 UTC, nicl-nno commented on gefest/tools/estimators/simulators/swan/swan_interface.py
>          Z = np.loadtxt(self.path_to_hs)
Тут большая Z тоже кажется не по PEP8.

2022-09-16 20:56 UTC, nicl-nno commented on gefest/tools/estimators/DL/bw_surrogate/bw_cnn.py
> +    Surrogate model for breakwaters task
Может тогда и cases перенести все-таки? Вряд ли это возможно для другой задачи переиспользовать в текущем виде (если возможно - то надо и назвать иначе, ассоциировов с каким-то классом задач).

2022-09-16 20:58 UTC, nicl-nno commented on gefest/tools/estimators/estimator.py
> +    def __init__(self, estimator, loss: Optional[Callable] = None):
Пометь тогда это TODO с описанием

2022-09-16 20:59 UTC, nicl-nno commented on cases/breakwaters/configuration_de/bw_optimizer.py
> +def configurate_optimizer(pop_size: int,
Пометь тогда это как TODO в коде. Ну и не-специфичную часть стоит все-таки вынести, чтобы не было повторяющегося кода.

2022-09-16 21:01 UTC, nicl-nno commented on cases/breakwaters/main.py
> +opt = parser.parse_args()
Норм, только названите opt какое-то непоняное. opt_params мб?

2022-09-16 21:02 UTC, nicl-nno commented on gefest/tools/estimators/simulators/swan/swan_model/INPUT2
> +$***********MODEL INPUT*********************************
Надо в названии указать, что это не one-for-all конфиг, а просто его example. Если надо - можно продублировать в cases, где он уже будет конкретен.

2022-09-16 21:05 UTC, nicl-nno commented
@pep8speaks pls update youself

2022-09-18 15:52 UTC, quickjkee commented on cases/breakwaters/configuration_de/bw_optimizer.py
> +def configurate_optimizer(pop_size: int,
пометил TODO

2022-09-18 15:52 UTC, quickjkee commented on cases/breakwaters/configuration_de/bw_sampler.py
> +def configurate_sampler(domain):
пометил TODO

2022-09-18 16:00 UTC, quickjkee commented on cases/breakwaters/configuration_spea2/bw_estimator.py
> +        root_path = Path(__file__).parent.parent.parent.parent
поправил

2022-09-18 16:00 UTC, quickjkee commented on cases/breakwaters/main.py
> +opt = parser.parse_args()
поменял

2022-09-18 16:02 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_model/INPUT2
> +$***********MODEL INPUT*********************************
если поменять название, то сван не запустится (не может найти инпут). Не смог найти, где нужно указывать имя инпута

2022-09-18 16:03 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_model/PRINT
> +1
теперь, вроде, исправилось

2022-09-18 16:03 UTC, quickjkee commented on gefest/tools/samplers/sampler.py
> +        self.sampler = sampler
сделал todo

2022-09-18 16:04 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_interface.py
>          Z = np.loadtxt(self.path_to_hs)
изменил

2022-09-18 16:40 UTC, nicl-nno commented on gefest/tools/estimators/simulators/swan/swan_model/INPUT2
> +$***********MODEL INPUT*********************************
Кажется swanrun.bat имя_инпута.

2022-09-20 11:56 UTC, quickjkee commented on gefest/tools/estimators/simulators/swan/swan_model/INPUT2
> +$***********MODEL INPUT*********************************
поменял

2022-09-23 21:55 UTC, quickjkee commented on cases/heat/configuration_dl/heat_estimator.py
> +def configurate_estimator(path_to_cnn=False):
пометил todo

2022-09-23 22:03 UTC, quickjkee commented on gefest/core/algs/geom/validation.py
> +    if poly_1 is poly_2 or len(poly_1.points) == 0 or len(poly_2.points) == 0:
видимо, здесь за что-то другое отвечает функция) в мейне так же. Если поставить 0, то генерация ломается. Пометил как todo, чтобы в дальнейшем разобраться

2022-09-23 22:03 UTC, quickjkee commented on gefest/core/opt/operators/mutation.py
> +                             y_scale=np.random.uniform(0.25, 3, 1)[0])
изменил по образу мейна

2022-09-23 22:03 UTC, quickjkee commented on gefest/core/opt/operators/mutation.py
> +    y_old = new_structure.polygons[polygon_to_mutate_idx].points[mutate_point_idx].y
теперь x new

2022-09-23 22:04 UTC, quickjkee commented on gefest/core/structure/prohibited.py
> +        target_polygons = [list(Point(target).buffer(20).exterior.coords) for target in targets]
пометил как todo, тк тоже не очень понимаю, что тут делается

2022-09-23 22:04 UTC, quickjkee commented on gefest/core/viz/struct_vizualizer.py
> +        fitness = info['fitness']
сделал как в мейне

2022-09-23 22:04 UTC, quickjkee commented on gefest/tools/estimators/DL/bw_surrogate/bw_cnn.py
> +    Surrogate model for breakwaters task
пометил todo

2022-09-23 22:04 UTC, quickjkee commented on gefest/tools/estimators/DL/heat/heat_cnn.py
> +class CNN:
пометил todo

2022-09-23 22:04 UTC, quickjkee commented on gefest/tools/estimators/estimator.py
> +    def __init__(self, estimator, loss: Optional[Callable] = None):
пометил

2022-09-23 22:04 UTC, quickjkee commented on gefest/tools/estimators/simulators/comsol/comsol_interface.py
> +class Comsol:
тоже сделал todo

2022-09-23 22:12 UTC, nicl-nno commented on gefest/core/opt/gen_design.py
> +        with open(f'{path}/performance_{i}.pickle', 'wb') as handle:
Лучше кстати Path использовать для сборки путей. Ну или хотя бы os.path.join. Чтобы не возникало межсистемный проблем со слешами.

2022-09-23 22:12 UTC, nicl-nno commented
TODO так TODO, но перед аппрувом поправь плз пункты 1, 2 и 4 (кое-где возвращаемые типы потерялись) из комментария выше.

2022-09-24 14:30 UTC, quickjkee commented on gefest/core/opt/gen_design.py
> +        with open(f'{path}/performance_{i}.pickle', 'wb') as handle:
поменял. возвращаемые типы и тд везде, вроде, учёл.

2022-09-27 14:07 UTC, merged